Kickoff api
wolox-training/acb-rails pull request #1
Opened 2018-09-11 17:44 UTC by agustinbajo

## **Initial Kickoff**
Data Base and user created successfully 

## **Trello Card** 
https://trello.com/c/wcgB4cfT

2018-09-11 18:12 UTC, leoncalermo requested changes
don't forget to delete commented code.

2018-09-11 18:12 UTC, leoncalermo commented on config/database.yml
> +#database: db/production.sqlite3
remove the commented code :eyes: .

2018-09-11 18:12 UTC, leoncalermo commented on config/database.yml
> +# database: nombre-de-tu-app_development
remove this commented code too :eyes: .

2018-09-11 19:20 UTC, agustinbajo commented
## **commit 0a42f53572f8fa6a880e002af13df993fe50e7bf**
- RuboCop Gem was added 
- All coments from database.yml were removed

2018-09-12 16:49 UTC, leoncalermo approved these changes
![all-good](https://media.giphy.com/media/l0MYDSv9mzn6Rar8A/giphy.gif) All good

2018-09-13 20:45 UTC, leoncalermo approved these changes
all good :ok_hand:

2018-09-13 21:02 UTC, merged