Index show test's
wolox-training/acb-rails pull request #6
Opened 2018-09-27 19:54 UTC by agustinbajo

https://trello.com/c/YbaCAE34

2018-09-28 20:05 UTC, leoncalermo requested changes

2018-09-28 20:05 UTC, leoncalermo commented on spec/controllers/api/v1/books_controller_spec.rb
> +        expect(response_body.to_json) =~ JSON.parse(expected)
here you can use expect().to eq() or something like that  instead of the =~

2018-09-28 20:05 UTC, leoncalermo commented on spec/controllers/api/v1/books_controller_spec.rb
> +        expect(response_body.to_json) =~ JSON.parse(expected)
also if you want to tests that the field validations you could use json schemas to validate the results, just as a tip :wink:

2018-09-28 20:05 UTC, leoncalermo commented on public/assets/.sprockets-manifest-33d6a223bc4d69f1df15bf0a3b3936d9.json
> +{"files":{"application-eaae6e935a232c711d293b3e22bd0f8a986b9be0b39f70a49e7b29977ad329f0.js":{"logical_path":"application.js","mtime":"2018-09-27T14:54:48-03:00","size":85961,"digest":"eaae6e935a232c7
what is this 🤔  ?

2018-09-28 21:44 UTC, agustinbajo commented
### Trello card's of this branch


- https://trello.com/c/YbaCAE34

- https://trello.com/c/OyZkoo3K

2018-10-01 14:11 UTC, leoncalermo approved these changes

2018-10-01 14:18 UTC, merged